Repository kategengler/playground-ghas, pull requests merged in 2022-08, with the labels that each got.

#17 Advance RFC #7773 to Stage Ready for Release
  text/7773-foo-bar.md
Labels: RFC Advancement, S-Ready for Release

#19 Advance RFC #0016 to Stage Ready for Release
  text/0016-foo-bar.md
Labels: RFC Advancement, S-Ready for Release

#20 Advance RFC #0016 to Stage Released
  text/0016-foo-bar.md
Labels: RFC Advancement, S-Released

#21 Advance RFC #0016 to Stage Recommended
  text/0016-foo-bar.md
Labels: RFC Advancement, S-Recommended

#23 Advance RFC #0022 to Stage Ready for Release
  text/0022-foo-bar.md
Labels: RFC Advancement, S-Ready for Release

#24 Advance RFC #0022 to Stage Released
  text/0022-foo-bar.md
Labels: RFC Advancement, S-Released

#25 Advance RFC #0022 to Stage Recommended
  text/0022-foo-bar.md
Labels: RFC Advancement, S-Recommended

#30 Advance RFC #0029 to Stage Ready for Release
  text/0029-foo-bar.md
Labels: RFC Advancement, S-Ready for Release

#31 Advance RFC #0029 to Stage Released
  text/0029-foo-bar.md
Labels: RFC Advancement, S-Released

#32 Advance RFC #0029 to Stage Recommended
  text/0029-foo-bar.md
Labels: RFC Advancement, S-Recommended

#42 Add RFC
  text/0030-foo-bar.md
Labels: S-Exploring

#47 Add rfc
  text/0032-foo-bar.md
Labels: S-Exploring

#49 Add RFC
  text/0049-foo-bar.md
Labels: bug, S-Exploring

#51 Add RFC
  text/0051-foo-bar.md
Labels: S-Exploring

#52 Modify rfcs
  text/0026-foo-bar.md
  text/0028-foo-bar.md
Labels: bug

#54 Add rfc
  text/0054-foo-bar.md
Labels: S-Exploring

#55 Try comparison with string
  text/0055-foo-bar.md
Labels: S-Exploring

#56 Advance RFC #0055 to Stage Ready for Release
  text/0055-foo-bar.md
Labels: RFC Advancement, S-Ready for Release

#67 Add rfc
  text/0067-foo-bar.md
Labels: S-Exploring

#68 Add rfc
  text/0068-foo-bar.md
Labels: S-Exploring

#69 Advance RFC #0068 to Stage Ready for Release
  text/0068-foo-bar.md
Labels: RFC Advancement, S-Ready for Release

#70 Advance RFC #0068 to Stage Released
  text/0068-foo-bar.md
Labels: RFC Advancement, S-Released

#71 Advance RFC #0068 to Stage Recommended
  text/0068-foo-bar.md
Labels: RFC Advancement, S-Recommended

#72 Add rfc
  text/0072-foo-bar.md
Labels: S-Exploring

#73 Add rFC
  text/0073-foo-bar.md
Labels: S-Exploring

#74 Advance RFC #0073 to Stage Ready for Release
  text/0073-foo-bar.md
Labels: RFC Advancement, S-Ready for Release

#75 Advance RFC #0073 to Stage Released
  text/0073-foo-bar.md
Labels: RFC Advancement, S-Released

#76 Advance RFC #0073 to Stage Recommended
  text/0073-foo-bar.md
Labels: RFC Advancement, S-Recommended

#78 Add rfc
  text/0078-foo-bar.md
Labels: S-Exploring

#80 Add rfc
  text/0080-foo-bar.md
Labels: S-Exploring

#82 Add rfc
  text/0082-foo-bar.md
Labels: S-Exploring

#84 Add RFC
  text/0084-foo-bar.md
Labels: S-Exploring

#85 Advance RFC #0084 to Stage Ready for Release
  text/0084-foo-bar.md
Labels: RFC Advancement, S-Ready for Release

#86 Advance RFC #0084 to Stage Released
  text/0084-foo-bar.md
Labels: RFC Advancement, S-Released

#87 Advance RFC #0084 to Stage Recommended
  text/0084-foo-bar.md
Labels: RFC Advancement, S-Recommended

#88 Add new RFC
  text/0088-pgengler.md
Labels: S-Exploring

#89 Advance RFC #0088 to Stage Ready for Release
  text/0088-pgengler.md
Labels: RFC Advancement, S-Ready for Release

#92 Advance RFC #0088 to Stage Released
  text/0088-pgengler.md
Labels: RFC Advancement, S-Released

#94 Advance RFC #0088 to Stage Recommended
  text/0088-pgengler.md
Labels: RFC Advancement, S-Recommended

#96 Add RFC
  text/0096-pgengler.md
Labels: bug, S-Exploring

#98 Add rfc
  text/0098-pgengler.md
Labels: S-Exploring

#100 Add rfc
  text/0100-pgengler.md
Labels: S-Exploring

#103 add rfc
  text/0103-pgengler.md
Labels: S-Exploring

#105 Add rfc
  text/0105-pgengler.md
Labels: S-Exploring

#106 Add rfc
  text/0106-pgengler.md
Labels: S-Exploring

#107 Advance RFC #0106 to Stage Ready for Release
  text/0106-pgengler.md
Labels: RFC Advancement, S-Ready for Release

#108 Advance RFC #0106 to Stage Released
  text/0106-pgengler.md
Labels: RFC Advancement, S-Released

#109 Advance RFC #0106 to Stage Recommended
  text/0106-pgengler.md
Labels: RFC Advancement, S-Recommended
